# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sonarResults

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - run: curl -u "fd88fe29c3526cdd8fe50ab1ad105d5c073f79c8":"https://sqprod.opsera.io" --url https://sqprod.opsera.io/api/measures/component?component=oswestry&metricKeys=new_bugs,new_vulnerabilities,new_security_hotspots
